apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-web-data
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Release.Name }}-web-data
  resources:
    requests:
      storage: 60Gi
